### ISSUE TITLE
forgive me, but I don't get this!

### ISSUE THREAD

**Issue by floer32** [fractaledmind/alfred_spritzr#1]
how do I spritz a document or a web page using this?

**Comment by fractaledmind** [comment]
This is a workflow for the app [Alfred](www.alfredapp.com/). So you need to use it via that interface. It also requires having the Alfred Power Pack (not the free version)

For a longer version of how exactly it works, view my post here: http://www.alfredforum.com/topic/4566-spritzr-an-alfred-speed-reading-workflow/

**Comment by fractaledmind** [comment]
Also, it does not spritz webpages. For that task, use the official Spritz bookmarklet, which can be found here: http://www.spritzinc.com/where-can-i-experience-spritz/

**Comment by floer32** [comment]
ahh That's what I wanted, the tutorial on the File Actions. Thanks!
